# Load libraries and run application
suppressWarnings(suppressMessages(library(dplyr)))
library(DT,warn.conflicts=FALSE)
library(ggplot2,warn.conflicts=FALSE)
library(glue,warn.conflicts=FALSE)
library(methods,warn.conflicts=FALSE)
library(MeltR,warn.conflicts=FALSE)
suppressWarnings(library(plotly,warn.conflicts=FALSE))
library(openxlsx,warn.conflicts=FALSE)
library(shiny,warn.conflicts=FALSE)
library(shinyjs,warn.conflicts=FALSE)
suppressWarnings(suppressMessages(library(ggrepel)))
library(remotes,warn.conflicts=FALSE)
suppressWarnings(library(shinythemes,warn.conflicts=FALSE))
runApp(launch.browser = TRUE)
